version: 2

models:
  - name: rolling_30_day_orders
    description: Aggregated completed orders over 30 days, sourced from stg_orders and stg_payments tables
    config:
      contract:
        enforced: true

    tests:
      - dbt_expectations.expect_column_pair_values_A_to_be_greater_than_B:
          column_A: rolling_30_day_amount
          column_B: total_amount
          or_equal: True

    columns:
      - name: order_date
        description: The date of the orders (truncated to date level)
        data_type: date
        tests:
          - not_null

      - name: total_amount
        description: Total payment amount for all completed orders on this date
        data_type: decimal(38,8)
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0
                max_value: 1000000  # Reasonable upper bound for daily totals

      - name: order_count
        description: Number of completed orders on this date
        data_type: decimal(38,8)
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0
                max_value: 10000  # Reasonable upper bound for daily order count

      - name: rolling_30_day_amount
        description: Sum of total_amount over the current date and previous 29 days
        data_type: decimal(38,8)
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0
                max_value: 30000000  # 30x the daily max

      - name: rolling_30_day_orders
        description: Sum of order_count over the current date and previous 29 days
        data_type: decimal(38,8)
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0
                max_value: 300000  # 30x the daily max

      - name: rolling_30_day_avg_daily
        description: Average daily total_amount over the current date and previous 29 days
        data_type: decimal(38,8)
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0
                max_value: 1000000  # Same as daily max