name: 'jaffle_shop'

config-version: 2
version: '0.1'

profile: 'jaffle_shop'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

data_tests:
  +store_failures: true

models:
  jaffle_shop:
      +persist_docs:
        relation: true
        columns: true
      schema: jaffle-shop-classic
      materialized: table
      staging:
        materialized: view
        +docs:
          node_color: '#C0C0C0'  # Silver
      marts:
        materialized: table
        +docs:
          node_color: '#B8860B'  # Dark Gold
      ddi:
        materialized: table
        schema: ddi
        +docs:
          node_color: '#B8860B'  # Dark Gold
      +docs:
        node_color: '#CD7F32'    # Bronze
