version: "3.9"

services:
  minio:
    image: minio/minio:latest
    container_name: jaffle-minio
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    command: server /data --console-address :9001
  iceberg-rest:
    image: tabulario/iceberg-rest:latest
    container_name: jaffle-iceberg-rest
    ports:
      - "8181:8181"
    environment:
      - CATALOG_WAREHOUSE=s3://warehouse/
      - CATALOG_IO__IMPL=org.apache.iceberg.aws.s3.S3FileIO
      - CATALOG_S3_ENDPOINT=http://minio:9000
      - CATALOG_S3_ACCESS_KEY_ID=minioadmin
      - CATALOG_S3_SECRET_ACCESS_KEY=minioadmin
      - CATALOG_S3_PATH_STYLE_ACCESS=true
    depends_on:
      - minio
  superset:
    image: apache/superset:latest
    container_name: jaffle-superset
    environment:
      SUPERSET_LOAD_EXAMPLES: "no"
      SUPERSET_SECRET_KEY: "secret"
      SQLALCHEMY_DATABASE_URI: sqlite:///app/superset_home/superset.db
    volumes:
      - superset-home:/app/superset_home
      - ./init_superset.sh:/app/init_superset.sh
    ports:
      - "8088:8088"
    command: /app/init_superset.sh
  trino:
    image: trinodb/trino:latest
    container_name: trino
    ports:
      - "8080:8080"
    environment:
      - DISCOVERY_URI=http://trino:8080
    volumes:
      - ./trino/etc:/etc/trino
    depends_on:
      - iceberg-rest
volumes:
    minio-data:
    superset-home:
