CREATE DATABASE superset;

-- Create schemas if they don't exist
CREATE SCHEMA IF NOT EXISTS staging;
CREATE SCHEMA IF NOT EXISTS marts;
CREATE SCHEMA IF NOT EXISTS ddi;
CREATE SCHEMA IF NOT EXISTS seeds;

-- Grant usage on schemas to dbt user
GRANT USAGE ON SCHEMA staging TO dbt;
GRANT USAGE ON SCHEMA marts TO dbt;
GRANT USAGE ON SCHEMA ddi TO dbt;
GRANT USAGE ON SCHEMA seeds TO dbt;

-- Grant select permissions on all tables in schemas to dbt user
GRANT SELECT ON ALL TABLES IN SCHEMA staging TO dbt;
GRANT SELECT ON ALL TABLES IN SCHEMA marts TO dbt;
GRANT SELECT ON ALL TABLES IN SCHEMA ddi TO dbt;
GRANT SELECT ON ALL TABLES IN SCHEMA seeds TO dbt;

-- Also grant permissions for future tables created in schemas
ALTER DEFAULT PRIVILEGES IN SCHEMA staging GRANT SELECT ON TABLES TO dbt;
ALTER DEFAULT PRIVILEGES IN SCHEMA marts GRANT SELECT ON TABLES TO dbt;
ALTER DEFAULT PRIVILEGES IN SCHEMA ddi GRANT SELECT ON TABLES TO dbt;
ALTER DEFAULT PRIVILEGES IN SCHEMA seeds GRANT SELECT ON TABLES TO dbt;